<a href="https://colab.research.google.com/github/mosigaaa/Credit---Score/blob/main/Recommendation_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework
[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/biodatlab/xlab-recommendation/blob/main/homework/homework.ipynb)

### 1. Implicit Recommendation with X-wines Dataset
Use [X-wines](https://github.com/rogerioxavier/X-Wines/tree/main/Dataset/last) dataset for implicit recommendation

##### Dataset preparation

In [1]:
# Download dataset from google drive
import gdown
output = "XWines_Slim_1K_wines_150K_ratings.zip"
url = "https://drive.google.com/file/d/1JuGLA56ibjPtzhupMxUHwA781XHT7Wml/view?usp=drive_link"
gdown.download(url=url, output=output, quiet=False, fuzzy=True)

# Extract dataset zip file
!unzip XWines_Slim_1K_wines_150K_ratings.zip

Downloading...
From: https://drive.google.com/uc?id=1JuGLA56ibjPtzhupMxUHwA781XHT7Wml
To: /content/XWines_Slim_1K_wines_150K_ratings.zip
100%|██████████| 2.47M/2.47M [00:00<00:00, 219MB/s]

Archive:  XWines_Slim_1K_wines_150K_ratings.zip
  inflating: XWines_Slim_150K_ratings.csv  
  inflating: XWines_Slim_1K_wines.csv  


In [ ]:
# TODO: Using implicit ALS model to get 10 wine recommendations for a single user.
# - Convert the dataset into an implicit one by setting ratings lower than 4.0 (or whatever threshold) to zero and those higher than 4.0 to one.
# - Weight the item-user sparse matrix with implicit BM25 weighting before creating an ALS model.
# - Display the result of the model with Gradio.

In [2]:
!pip install implicit
!pip install gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 35.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.4/15.4 MB 41.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.9/92.9 kB 10.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.7/302.7 kB 30.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 30.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 kB 16.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.8/395.8 kB 41.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 5.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 16.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 92.0 M

In [3]:
import pandas as pd
import numpy as np

In [4]:
Xwine_rating_1K = pd.read_csv("/content/XWines_Slim_1K_wines.csv")
Xwine_rating_150K = pd.read_csv("/content/XWines_Slim_150K_ratings.csv")
#print(Xwine_rating_1K.head(10))
print(Xwine_rating_150K.head(10))

   RatingID   UserID  WineID Vintage  Rating                 Date
0       143  1356810  103471    1950     4.5  2021-11-02 20:52:59
1       199  1173759  111415    1951     5.0  2015-08-20 17:46:26
2       348  1164877  111395    1952     5.0  2020-11-13 05:40:26
3       374  1207665  111433    1953     5.0  2017-05-05 06:44:13
4       834  1075841  111431    1955     5.0  2016-09-14 20:18:38
5       876  1211463  111395    1955     5.0  2021-12-02 23:12:49
6      1005  1076348  111433    1955     4.5  2021-06-19 19:53:56
7      1020  1147051  111429    1955     5.0  2018-07-08 20:09:46
8      1029  1225931  111431    1955     5.0  2017-04-24 01:41:52
9      1399  1197513  111415    1958     5.0  2014-07-04 01:07:16


<ipython-input-4-4a2c5e755d00>:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  Xwine_rating_150K = pd.read_csv("/content/XWines_Slim_150K_ratings.csv")


In [5]:
Xwine_rating_150K.drop(columns=["Date"],inplace=True)

for index, rating in Xwine_rating_150K["Rating"].iteritems():
    if rating > 4:
        Xwine_rating_150K.at[index, "Rating"] = 1
    else:
       Xwine_rating_150K.at[index, "Rating"] = 0

<ipython-input-5-dffef22c8b4c>:3: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for index, rating in Xwine_rating_150K["Rating"].iteritems():


In [6]:
print(Xwine_rating_150K["Rating"].value_counts())

0.0    116442
1.0     33558
Name: Rating, dtype: int64


In [7]:
from sklearn.decomposition import NMF
from scipy.sparse import csr_matrix
from implicit.nearest_neighbours import bm25_weight

In [10]:
Xwine_rating_150K["Rating"] = Xwine_rating_150K["Rating"].astype(float)
Xwine_rating_150K["UserID"] = Xwine_rating_150K["UserID"].astype("category")
Xwine_rating_150K["WineID"] = Xwine_rating_150K["WineID"].astype("category")

In [11]:
X_rating = csr_matrix( (
    Xwine_rating_150K["Rating"],(Xwine_rating_150K["UserID"].cat.codes,Xwine_rating_150K["WineID"].cat.codes)
    )
)
X_rating = X_rating.tocsr()
print(X_rating)

  (0, 68)	0.0
  (0, 161)	0.0
  (0, 191)	0.0
  (0, 195)	0.0
  (0, 197)	1.0
  (0, 199)	1.0
  (0, 204)	0.0
  (0, 206)	0.0
  (0, 215)	1.0
  (0, 218)	1.0
  (0, 270)	0.0
  (0, 382)	0.0
  (0, 399)	0.0
  (0, 418)	0.0
  (0, 439)	0.0
  (0, 521)	0.0
  (0, 522)	0.0
  (0, 545)	0.0
  (0, 560)	0.0
  (0, 642)	0.0
  (0, 649)	0.0
  (0, 717)	1.0
  (0, 765)	1.0
  (0, 783)	0.0
  (0, 811)	0.0
  :	:
  (10559, 211)	0.0
  (10559, 226)	0.0
  (10559, 243)	0.0
  (10559, 353)	0.0
  (10559, 563)	1.0
  (10559, 637)	0.0
  (10559, 642)	0.0
  (10559, 652)	0.0
  (10559, 781)	0.0
  (10559, 920)	0.0
  (10559, 923)	0.0
  (10560, 53)	0.0
  (10560, 63)	0.0
  (10560, 141)	0.0
  (10560, 204)	1.0
  (10560, 210)	0.0
  (10560, 220)	0.0
  (10560, 237)	0.0
  (10560, 256)	0.0
  (10560, 264)	0.0
  (10560, 377)	0.0
  (10560, 516)	0.0
  (10560, 641)	0.0
  (10560, 906)	1.0
  (10560, 912)	0.0


In [20]:
from implicit.nearest_neighbours import bm25_weight

X_rating = bm25_weight(X_rating, K1=100, B=0.8)
print(X_rating)
from implicit.als import AlternatingLeastSquares
model = AlternatingLeastSquares(factors=64, regularization=0.05, alpha=2.0)
# Implicit expect user-item (user-artist)
user_rating = X_rating.T.tocsr()

model.fit(user_rating)


  (0, 68)	0.0
  (0, 161)	0.0
  (0, 191)	0.0
  (0, 195)	0.0
  (0, 197)	112.0345526687692
  (0, 199)	96.28680155720033
  (0, 204)	0.0
  (0, 206)	0.0
  (0, 215)	140.31743599945386
  (0, 218)	167.1898101545216
  (0, 270)	0.0
  (0, 382)	0.0
  (0, 399)	0.0
  (0, 418)	0.0
  (0, 439)	0.0
  (0, 521)	0.0
  (0, 522)	0.0
  (0, 545)	0.0
  (0, 560)	0.0
  (0, 642)	0.0
  (0, 649)	0.0
  (0, 717)	123.8302282565163
  (0, 765)	81.4841587608406
  (0, 783)	0.0
  (0, 811)	0.0
  :	:
  (10559, 211)	0.0
  (10559, 226)	0.0
  (10559, 243)	0.0
  (10559, 353)	0.0
  (10559, 563)	201.51758380611193
  (10559, 637)	0.0
  (10559, 642)	0.0
  (10559, 652)	0.0
  (10559, 781)	0.0
  (10559, 920)	0.0
  (10559, 923)	0.0
  (10560, 53)	0.0
  (10560, 63)	0.0
  (10560, 141)	0.0
  (10560, 204)	178.03714296097837
  (10560, 210)	0.0
  (10560, 220)	0.0
  (10560, 237)	0.0
  (10560, 256)	0.0
  (10560, 264)	0.0
  (10560, 377)	0.0
  (10560, 516)	0.0
  (10560, 641)	0.0
  (10560, 906)	142.5782474781955
  (10560, 912)	0.0


  0%|          | 0/15 [00:00<?, ?it/s]

In [21]:
import gradio as gr


def recommend_wine(user_id):
    user_id = int(user_id)
    if (
        Xwine_rating_150K["UserID"] == user_id
    ).any():  # check if input user_id exist in dataset or not
        selected_user_df = Xwine_rating_150K[Xwine_rating_150K["UserID"] == user_id].sort_values(
            by="Rating", ascending=False
        )

        # Get the user index for the user_id to use in the prediction
        user_idx = selected_user_df["UserID"].cat.codes.values[0]
        predicted_ratings = np.dot(W[user_idx], H)
        sort_rating_indices = np.flip(np.argsort(predicted_ratings))[:20]
        selected_predict_ratings = predicted_ratings[sort_rating_indices]

        # Get the WineID from the sorted indices
        rec_wine_ids = Xwine_rating_150K["WineID"].cat.categories[sort_rating_indices]

        rec_df = pd.DataFrame({
            "WineID": rec_wine_ids,
            "PredictedRating": selected_predict_ratings,
        })

        # Merge with the original dataset to get additional wine details
        rec_df = rec_df.merge(Xwine_rating_150K.drop_duplicates(subset=['WineID']), how="left", on="WineID")

        # Return the top 10 actual ratings by the user and top 10 recommendations
        return selected_user_df.head(10), rec_df.head(10)
    else:
        raise gr.Error("User ID not found")

# Gradio interface setup
demo = gr.Interface(
    fn=recommend_wine,
    inputs=gr.Textbox(label="Input UserID (e.g., from 1 - 610)"),
    outputs=[gr.DataFrame(label="User's Rated Wines"), gr.DataFrame(label="Recommended Wines")],
    examples=["21", "50"],
).launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://4311dbb0f6ece6ebfd.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


### 2. Using CLIP to embed product images and recommend similar items
Use [fashion-product-images](https://www.kaggle.com/datasets/paramaggarwal/fashion-product-images-dataset) dataset for CLIP image search

* Dataset: https://www.kaggle.com/datasets/paramaggarwal/fashion-product-images-dataset
* Interface with Kaggle API: https://www.kaggle.com/discussions/general/74235

##### Dataset preparation

In [29]:
!pip install kaggle

In [31]:
# follow the "interface with Kaggle API" link, upload kaggle.json

from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"makkawanchaimongkol","key":"c6687734fccb0256c9f2f480547ab078"}'}

In [32]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [33]:
# test access kaggle dataset
!kaggle datasets list

ref                                                         title                                             size  lastUpdated          downloadCount  voteCount  usabilityRating  
----------------------------------------------------------  -----------------------------------------------  -----  -------------------  -------------  ---------  ---------------  
iamsouravbanerjee/customer-shopping-trends-dataset          Customer Shopping Trends Dataset                 146KB  2023-10-05 06:45:37          19388        411  1.0              
prasad22/healthcare-dataset                                 Healthcare Dataset                               483KB  2023-10-31 11:30:58            793         25  1.0              
rajatsurana979/fast-food-sales-report                       Restaurant Sales report                          122KB  2023-11-06 20:46:39            924         31  1.0              
nelgiriyewithana/billionaires-statistics-dataset            Billionaires Statistics Dataset (20

In [34]:
# download dataset

!kaggle datasets download -d paramaggarwal/fashion-product-images-small

 99% 562M/565M [00:19<00:00, 33.2MB/s]
100% 565M/565M [00:19<00:00, 30.2MB/s]


In [ ]:
# extract dataset zip file

!unzip fashion-product-images-small.zipฤ

In [ ]:
! pip install torch ftfy regex tqdm numpy
! pip install openai-clip
! pip install gradio
! pip install gdown

In [38]:
import os
import os.path as op
from PIL import Image
from zipfile import ZipFile

import numpy as np
from tqdm import tqdm
import torch

import clip
# check available runtime

device = "cuda" if torch.cuda.is_available() else "cpu"
if device == "cuda":
  ! pip install faiss-gpu
else:
  ! pip install faiss-cpu

print("Now running with " + device)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 MB 9.3 MB/s eta 0:00:00
Now running with cuda


In [39]:
clip.available_models()

['RN50',
 'RN101',
 'RN50x4',
 'RN50x16',
 'RN50x64',
 'ViT-B/32',
 'ViT-B/16',
 'ViT-L/14',
 'ViT-L/14@336px']

In [41]:
model, preprocess = clip.load("ViT-B/32", device=device)

100%|███████████████████████████████████████| 338M/338M [00:12<00:00, 28.8MiB/s]


In [59]:
# load dataset

dataset_path = op.join(os.getcwd(), "/content/myntradataset/images/")
print(dataset_path)

/content/myntradataset/images/


In [60]:
# create list of all filename in dataset folder

all_folder_path = os.listdir(dataset_path)
all_folder_path.sort()
print(len(all_folder_path))

44441


In [87]:
# allocate embeddings array from num_file
embeddings_storage = np.zeros((len(all_folder_path),512),dtype=np.float32)

# encoder dataset & store images name
file_counter = 0
images_path = [f for f in os.listdir(dataset_path) if op.isfile(op.join(dataset_path, f))]
images_path.sort()
for path in tqdm(images_path):
    with torch.no_grad():
        image = (
            preprocess(Image.open(op.join(dataset_path, path))).unsqueeze(0).to(device)
        )
        embeddings_storage[file_counter] = np.array(
            model.encode_image(image).numpy(force=True)[0].astype("float32")
        )
        file_counter += 1



100%|██████████| 44441/44441 [12:00<00:00, 61.67it/s]


In [88]:
# create embeddings vector using FAISS

import faiss

index = faiss.IndexFlatL2(
    512
)  # dimension of 1 embedding decoded from CLIP model is 512
index.add(embeddings_storage)
print(index.ntotal)

44441


In [91]:
import gradio as gr
from PIL import Image
import numpy as np
import os.path as op
import torch



def recommend_similar_image(image_path):
    print(f"get image path {image_path}")

    test_image = preprocess(Image.open(image_path)).unsqueeze(0).to(device)

    with torch.no_grad():
        test_embeddings = model.encode_image(test_image).numpy(force = True)[0].astype("float32")
        test_embeddings = np.array([test_embeddings])

    k = 4  # number of recommendations
    square_distance, image_index = index.search(test_embeddings, k)
    print(image_index)
    print(square_distance)

    print("Opening Images...")
    recommended_images = [
        (
            Image.open(op.join(dataset_path, all_folder_path[image_index[0][i]])),
            f"Recommended Rank {i+1}",
        )
        for i in range(k)
    ]
    return recommended_images


demo = gr.Interface(
    fn=recommend_similar_image,
    inputs=gr.Image(type="filepath"),
    outputs=gr.Gallery(),
).launch(share=True, debug=True)


Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
Running on public URL: https://4e8e1a3b5bf3ec3be4.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


get image path /tmp/gradio/941c0fffed299a38aa131564a19d0d739f3ece66/image.png
[[    6 41468 15906 42396]]
[[ 0.       10.718597 11.229553 14.982812]]
Opening Images...
Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7861 <> https://4e8e1a3b5bf3ec3be4.gradio.live


In [ ]:
def recommend_similar_image(text):

    text = clip.tokenize([text]).to(device)
    with torch.no_grad():
        test_embeddings = model.encode_text(text).numpy(force=True)[0].astype("float32")
        test_embeddings = np.array([test_embeddings])

    k = 10  # number of recommendations
    square_distance, image_index = index.search(test_embeddings, k)
    print(image_index)
    print(square_distance)

    print("Opening Images...")
    recommended_images = [
        (
            Image.open(op.join(dataset_path, all_folder_path[image_index[0][i]])),
            f"Recommended Rank {i+1}",
        )
        for i in range(k)
    ]
    return recommended_images


example_path = []
demo = gr.Interface(
    fn=recommend_similar_image,
    inputs=gr.Textbox(),
    outputs=gr.Gallery(),
).launch(share=True, debug=True)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
Running on public URL: https://0d58e9a8da8d422b44.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


[[11286 33505 25976 12611 42482 13143  2598 20572 31812 17311]]
[[119.534355 120.381744 120.83953  122.36725  123.34304  123.40774
  123.564995 123.65398  123.70002  123.93276 ]]
Opening Images...
[[  661 28304 41571 38655 28299 16776 42585 42442 27336 28590]]
[[176.1723  179.19489 179.34119 179.75227 180.8226  181.25922 181.40344
  181.49213 181.76077 182.04488]]
Opening Images...
[[34227 28590 32743 42585  3796  4570 11286 28593 28895 11163]]
[[166.98631 167.86702 167.96751 167.99074 168.2092  168.29666 168.35619
  168.37315 168.41467 168.43793]]
Opening Images...
[[28081 43800 41571 28304 28299 37329 12611 28047 42442 11958]]
[[151.98413 152.98402 153.1293  154.42413 154.8538  154.895   155.10371
  155.32512 155.42017 155.5368 ]]
Opening Images...
[[20948 37351  9431 26266  4401  3125 30951 16603 38866  2516]]
[[127.45049 128.10587 128.65756 128.78375 129.0273  129.19585 129.55028
  129.66087 129.70586 129.72473]]
Opening Images...
[[28360 37329 28304 41571  3745 38866 41568 28299 2